name: Android adhoc
on:
  push:
    branches:
      - main
jobs:
  export_android:
    name: TestAppIo app distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          distribution: 'zulu'
          java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
         flutter-version: '2.10.4'
    - name: Build release
    - run: flutter pub get
    - run: flutter build apk

    - name: Upload IPA to TestApp.io
      uses: testappio/github-action@v5
      with:
        api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
        app_id: ${{secrets.TESTAPPIO_APP_ID}}
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        release_notes: "Testing manual release notes..."
        git_release_notes: true
        include_git_commit_id: false
        notify: true